name: Create Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./cmd/secure-import
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Build
        run: |
          go build -v -o bin/helm-secure-import-linux-amd64
          GOOS=windows GOARCH=amd64 go build -v -o bin/helm-secure-import-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -v -o bin/helm-secure-import-macos-amd64
          GOOS=darwin GOARCH=arm64 go build -v -o bin/helm-secure-import-macos-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cmd/secure-import/bin/*
          draft: false
          prerelease: false
          generate_release_notes: true